### ISSUE TITLE
define own filters

### ISSUE THREAD

**Issue by emilos** [buxlabs/boxwood#371]
```html
{"foo" | bar}
```

where `bar` would be a function that was passed as an option to the compiler.

```js
await compile('{"foo" | bar}', { filters: { bar (value) { return value + "bar" } })

**Comment by pkonieczniak** [comment]
There is no problem when custom filter is named:
```
  let template = await compile('{foo | myFilter}', {
    filters: {
      myFilter: function myFilter (text) {
        return text.toUpperCase()
      } 
    }
  })
```

In case when someone defined function as anonymous or arrow fn then we cannot create AST.

In first example we received error `Function declaration must have a name in this context`
For case:
```js
filters: {
 myFilter: function () {}
}
```
For this case we can return a new Function an append the name.

I think that more complex is handling arrow functions.

Babel has some plugins which can be used via node (transform-function-name, plugin-transform-arrow-functions)
