### ISSUE TITLE
Markdown - Handle template variables

### ISSUE THREAD

**Issue by pkonieczniak** [buxlabs/boxwood#472]

**Comment by emilos** [comment]
The following works:

```
<markdown>hello, world</markdown>
```

The following does not work:

```
<markdown>{foo}</markdown>
```

To support this use case, we'd need to do the following

```js
function render () {
  // we need to define the full markdown lib here

   __t += markdown(__o.foo)

}
```


the user can do it on his own easily though, by:

```js
{ markdown(foo) }
```

so it might not be needed as it's not a general use case.
