### ISSUE TITLE
Generalize i18n to data

### ISSUE THREAD

**Issue by zaiste** [buxlabs/boxwood#600]
Currently we have this

```
<i18n yaml>
hello:
- 'Hej!'
- 'Hello!'
</i18n>
```

I propose to generalize this approach by replacing the `i18n` tag with the folllowing `data` tag:

```
<data yaml>
hello:
  en: Hello
  pl: Siema
</data>
```

We could then keep the `translate` tag and design it so that it expects the data in the shape as defined above, otherwise this could be used to simply define local data.

**Comment by emilos** [comment]
interesting, how would you know that data is for translations vs being local?

**Comment by zaiste** [comment]
@emilos this could be the *shape* of data, e.g. the `translate` would look for the `i18n` top level key:

```
i18n:
  hello:
    en: Hello
    pl: Siema
```

**Comment by emilos** [comment]
I like the idea! The only question left is how to access the data from a scoped script:

```html
<script scoped>
   console.log(scope.data) // maybe this way?
</script>
```

**Comment by zaiste** [comment]
@emilos Interesting. And what would be wrong with using `this` instead of `scope` in this context ? I'm looking for familiar constructs/names, but maybe this would mess things too much ?

**Comment by emilos** [comment]
@zaiste there's probably nothing wrong with using `this`. It's a strong keyword thought so I didn't want to take it yet until I figure out the edge cases.

There's also one technical implication, it's also a little bit easier to manipulate a variable like `scope` than having to traverse through an abstract syntax tree and rename `this` to something else. Wanted to avoid this for now and experiment a bit first.

I'm still trying to figure out the best interface for accessing variables, here're some examples:

a) have a way to access local variables (e.g. like defined in `data`)
b) have a way to access global variables (e.g. the ones passed to the main template, usually things like  `language`, `context`, `url` etc.)
c) have a way to use built-in helpers in scoped scripts (e.g. translate)
d) live updates (later)

**Comment by emilos** [comment]
@zaiste implemented here https://github.com/buxlabs/boxwood/pull/601
