### ISSUE TITLE
CSS Selectors inspired syntax

### ISSUE THREAD

**Issue by zaiste** [buxlabs/boxwood#607]
**This is low priority** Just posting it for brainstorming.

How about writing this:

```html
<h1#name.boo.foo>Header 1</h1>
```

instead of this:

```html
<h1 id="name" class="boo foo">Header 1</h1>
```

as an optional syntax shortcut ?

**Comment by emilos** [comment]
I like the idea, less typing is usually nice, wouldn't hurt if it's optional.

Leaving some implementation notes here:

- [ ] should be either implemented as a part of the `Transpiler` or as a new `Plugin`, e.g. `ShortSyntaxPlugin` or something similar.
- [ ] unit tests
- [ ] acceptance spec that imports deps using the new syntax
