### ISSUE TITLE
Access content from the data tag as values

### ISSUE THREAD

**Issue by zaiste** [buxlabs/boxwood#608]
Given this markup 

```html
<div>{foo}</div>
```

and the data definition within the **same** Boxwood file

```html
<data yaml>
foo: This is foo
</data>
```

I'd like to get the following render

```html
<div>This is foo</div>
```

The values defined in the markup/component should overwrite inherited values with the same names - similar to how it works in programming languages with local, parent and global scope.

**Comment by emilos** [comment]
It makes sense and I've been looking into implementing this as a `<var>` tag, but data makes it a bit easier to keep it in one place and allows to use different syntaxes.

Some implementation notes:

- [ ] parse data tag (tags/data.js) and add data to `variables` or `localVariables`
- [ ] acceptance test with imported components that use this feature
- [ ] unit tests
- [ ] update README

**Comment by emilos** [comment]
@zaiste I've released a basic implementation under `v0.27.0`, docs are here: https://github.com/buxlabs/boxwood/blob/master/README.md#data

There's a lot of room for cleanup here fo sure.

Thanks again!

**Comment by emilos** [comment]
@zaiste one last note: data tag has to be defined above usage. I left a todo for that (will convert all todos  to issues when I have more time).

**Comment by zaiste** [comment]
@emilos wow, this is great! Thank you!
