### ISSUE TITLE
Nesting layouts (or layout inheritance) is not possible

### ISSUE THREAD

**Issue by zaiste** [buxlabs/boxwood#609]
I'm trying to inherit from a layout with the following setup

`base` layout

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <h1>Base Layout</h1>
  <slot />
</body>

</html>
```

`docs` layout

```html
<import base from="base.html" />

<base>
  <h1>Inside Docs</h1>
  <slot />
</base>
```

finally a documentation page that inherits from the `docs`

```html
<import layout from='layouts/docs.html' />

<layout>
  <h1>Specific Doc</h1>
</layout
```

I'm getting:

```
RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
internal/process/promises.js:80
      unhandledRejection(promise, reason);
```

**Comment by emilos** [comment]
@zaiste thanks! really helpful

**Comment by emilos** [comment]
@zaiste I've tackled it here quickly https://github.com/buxlabs/boxwood/pull/610 and pushed `v0.25.0`. Definitely not the final solution and we might up failing into related issues, but this should be good enough for simple cases.

**Comment by zaiste** [comment]
@emilos It works like a charm! Thank you
