### ISSUE TITLE
Small Markdown -> Unescape issue

### ISSUE THREAD

**Issue by zaiste** [buxlabs/boxwood#611]
I'm converting Markdown into HTML, then I insert this converted snippet into my Boxwood layout using

```
{content | unescape }
```

Here's a snippet generated by the `markdown-it` library:

```html
<pre><code>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>if</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>for</span><span class="token punctuation">></span></span>
</code></pre>
```

This should generate:

```html
</if>
</for>
```

This is also how it works in the browser.

In Boxwood, however, the `&lt;` character is treated differently. I cannot pinpoint why is that. As a result I'm getting this:

```
if>
for>
```

**Comment by emilos** [comment]
@zaiste thanks, I'll investigate :). In the meantime, could you try:

```html
<div html="{content}"></div>
```

Generally the syntax `{}` is almost always escaped, and the current way to embed html is the `html` attribute to make it a little bit harder to use.

**Comment by zaiste** [comment]
@emilos it worked! I propose to either close it or assign a `low priority` label. What do you think ?

**Comment by emilos** [comment]
@zaiste cool :) I'll leave it open, might be worth doing the following:

- [ ] update docs and mention how to inject html (mention potential security risk and add an example)
- [ ] investigate if `unescape` works correctly
