### ISSUE TITLE
script[routes]

### ISSUE THREAD

**Issue by emilos** [buxlabs/boxwood#622]
setup:

```js
// ...
const { template } = await compile(source, {
  routes: {
    Users: {
      browse: '/rest/users'
    }
  }
})
// ...
```

input:

```html
<script routes>
const url = route('Users.browse')
</script>
```

output:

```html
<script routes>
const url = '/rest/users'
</script>
```

**Comment by zaiste** [comment]
@emilos Nice! I'll keep the names in the singular form for coherence (as described [here](https://kretes.dev/docs/in-depth/rest/)) i.e. 

`User.browse` -> `/user`

I'm not sure about the prefix. Maybe this could be configurable?

**Comment by emilos** [comment]
@zaiste I agree, could also be something like:

 `Routes.get(`
`routes.get(`

so that we can have other options like:

`routes.has(`
`routes.each(`

etc.
