### ISSUE TITLE
Better error message when css file is not found

### ISSUE THREAD

**Issue by emilos** [buxlabs/boxwood#648]
Given a file that does not exist:

```html
<link rel="stylesheet" href="assets/css/main.css" inline>
```

 we're currently showing an error:

`Component not found ...`

It'd be a bit better if in this case it'd say:

`Stylesheet not found ...`

**Comment by inikonorov** [comment]
https://github.com/buxlabs/boxwood/pull/650

**Comment by emilos** [comment]
@inikonorov thanks!
