### ISSUE TITLE
Error is occured in pre-push hook

### ISSUE THREAD

**Issue by inikonorov** [buxlabs/boxwood#662]
![image](https://user-images.githubusercontent.com/30556799/100137375-30a15a00-2eae-11eb-971d-7fd72798c193.png)
When I push changes I get an error in pre-push hook, is it okay?

**Comment by emilos** [comment]
@inikonorov please try reinstalling the dependencies, I have updated `esbuild` recently.

**Comment by inikonorov** [comment]
okay, everything is fine, close.
